name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: generated-zip
          file_path: security-threads-${{ env.CURRENT_DATE }}.zip
